version: '3.4'

services:
  tinyurl.webapi:
    image: ${DOCKER_REGISTRY-}tinyurlwebapi
    build:
      context: .
      dockerfile: TinyUrl.WebApi/Dockerfile
  # redis.cache:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  mongodb.database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
 # redis_data:
